# 服务器端口，如果不配置默认是80端口
server:
  port: 8088
  servlet:
    context-path: /xwxsb


max-http-header-size: 102400
# 数据库设置
spring:
  application:
    name: myf
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myf?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 40
      max-lifetime: 1800000
      idle-timeout: 60000
      minimum-idle: 5
    devtools:
      restart:
        enabled: true
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 5000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 40 # 最大活动连接数
        max-idle: 10 # 最大空闲连接数
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 获取连接时的最大等待时间（负数表示无限等待）






